### ISSUE TITLE
The bundle "rubocop" could not be installed because it is malformed

### ISSUE THREAD

**Issue by johnivanoff** [mrdougal/textmate2-rubocop#6]
"The bundle lacks mandatory keys in its property list file."

I followed the instructions using Git.

Textmate:
TextMate version 2.0-alpha.9515

OS 
mac 10.9.2

![screen shot 2014-03-21 at 9 22 32 am](https://f.cloud.github.com/assets/8841/2483760/976df8bc-b104-11e3-8e71-013521d082b2.png)

**Comment by mrdougal** [comment]
Thanks for your bug report John. 
Unfortunately I haven't been able to replicate the issue yet…
I've tried on my own machine, and my wife's mac (on a fresh install of TM2)

I assume you cloned the repo to your desktop, then double clicked it, so that TM2 too over the install? As i've found cloning directly into `~/Library/Application\ Support/Avian/Bundles` can cause  issues.

**Comment by johnivanoff** [comment]
I didn't have the bundles directory. 
Creating that directory and then following your instructions worked. :-)
$ mkdir -p ~/Library/Application\ Support/Avian/Bundles/

Thank you

**Comment by mrdougal** [comment]
Ok i'll close this now, and i'll try to clarify the install instructions in the readme
